### ISSUE TITLE
[RFC] Library Roadmap

### ISSUE THREAD

**Issue by bell-steven** [FaridSafi/react-native-google-places-autocomplete#552]
Short term goals:
- [x] Add a table with a list of all available props.
- [x] Review all of the open PRs
- [x] Fix critical bugs in the library
- [x] Using Current location is broken in RN v0.60.0+ (#541)
- [x] Triage all of the open issues
- [x] Enable web support (by using a proxy server)
- [x] add typescript definitions

Long terms goals:
- [x] Provide a clear write up about the difference Google APIs this library utilizes.
- [x] Bring the codebase inline with some of newer react/react-native features and patterns.
- [x] Update typescript definitions, propTypes and Readme with all of the available props. 
- [ ] Update documentation with clear examples
- [ ] Update Examples in the example folder
- [ ] modernize the codebase so that the library is easier to work with and contribute to. 
- [ ] Cut down on the number of props (there are currently 41 props available)
- [ ] Explore splitting up the component based on the type of Google Maps API you want to use.

**If you are willing to contribute by taking a task and creating PRs, that would be most appreciated (and will really speed things up)**. Sound off below

**Comment by ynigoreyes** [comment]
Hi! Which props are you thinking of getting rid of? Where can I find more information about getting started on that one? @bell-steven

**Comment by bell-steven** [comment]
I have a google sheet you can view [here](https://docs.google.com/spreadsheets/d/1M5oFbtv5AlROzDMLhpCTJLqWIt08MdO8Nor6DQK7iR8/edit?usp=sharing).  It's still a work in progress.

**Comment by strdr4605** [comment]
>  Look into splitting up the component based on the type of Google Maps API you want to use.
I think this library serves only one propose and I don't see any reasonable splitting! Can you elaborate?!

**Comment by bell-steven** [comment]
@strdr4605 the library in its current state can do a few things. 
1) autocomplete an address/place search
2) find nearby places
3) get address from current location
4) get place details from address/place search

Each of these functions uses a different api, and has unique query parameters. I wrote a pretty detailed breakdown of all of this [here](https://github.com/FaridSafi/react-native-google-places-autocomplete/issues/373#issuecomment-633331299).

The idea would be to 'split' some of the functionality up to make it easier to use the library.
As an example 
```
import { GooglePlacesAutocomplete } from "react-native-google-places-autocomplete"
```
might turn into something like 
```
import { GetNearbyPlaces, GoogleAutoComplete, GetAddressFromLocation } from "react-native-google-places-autocomplete"

```

**Comment by bell-steven** [comment]
I created a `v2` branch.  Please create all breaking/major changes against that branch.

**Comment by bell-steven** [comment]
Is there anyone here who can help with some typescript definitions?

**Comment by QuintonC** [comment]
Would be it be feasible to request the ability to customize the Current Location button? 

E.g. I'd like to be able to give it props or pass it a function to render a pre-defined button.

**Comment by bell-steven** [comment]
@QuintonC  this sounds like a question/feature request. Please open a separate issue.
